export const top30Dax = [
    {name: 'Adidas', symbol: 'ADS'},
    {name: 'Allianz', symbol: 'ALV'},
    {name: 'BASF', symbol: 'BAS'},
    {name: 'Bayer', symbol: 'BAYN'},
    {name: 'Beiersdorf', symbol: 'BEI'},
    {name: 'BMW', symbol: 'BMV'},
    {name: 'Commerzbank', symbol: 'CBK'},
    {name: 'Continental', symbol: 'CON'},
    {name: 'Daimler', symbol: 'DAI'},
    {name: 'Deutsche Bank', symbol: 'DBK'},
    {name: 'Deutsche Börse', symbol: 'DB1'},
    {name: 'Lufthansa', symbol: 'LHA'},
    {name: 'Deutsche Post', symbol: 'DPW'},
    {name: 'Deutsche Telekom', symbol: 'DTE'},
    {name: 'E.ON', symbol: 'EOAN'},
    {name: 'Fresenius', symbol: 'FRE'},
    {name: 'Fresenius Medical Care', symbol: 'FME'},
    {name: 'HeidelbergCement', symbol: 'HEI'},
    {name: 'Henkel', symbol: 'HEN3'},
    {name: 'Infineon', symbol: 'IFX'},
    {name: 'Linde', symbol: 'LIN'},
    {name: 'Merck', symbol: 'MRK'},
    {name: 'Munich Insurance', symbol: 'MUV"'},
    {name: 'ProSiebenSat1', symbol: 'PSM"'},
    {name: 'RWE', symbol: 'RWE"'},
    {name: 'SAP', symbol: 'SAP"'},
    {name: 'Siemens', symbol: 'SIE"'},
    {name: 'Thyssenkrupp', symbol: 'TKA"'},
    {name: 'Volkswagen', symbol: 'VOW3"'},
    {name: 'Vonovia', symbol: 'VNA"'},
];